"""init

Revision ID: 73d9f1177e17
Revises: 
Create Date: 2025-05-12 19:00:52.169965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d9f1177e17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries'))
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_name'), ['name'], unique=True)

    op.create_table('products_countries',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_products_countries_country_id_countries')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_products_countries_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'country_id', name=op.f('pk_products_countries'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=32), autoincrement=False, nullable=True))

    op.drop_table('products_countries')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_name'))

    op.drop_table('countries')
    # ### end Alembic commands ###
